version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ecoexp
      - MYSQL_USER=ecoexp
      - MYSQL_PASSWORD=ecoexp
    restart: always
    volumes:
      - ./etc/mysql/utf.cnf:/etc/mysql/conf.d/utf.cnf
      - ./etc/mysql/auth.cnf:/etc/mysql/conf.d/auth.cnf
      - ./src/main/resources/create-proc.sql:/proc.sql
      - ./etc/mysql/create-proc.sh:/proc.sh
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8081:80
