version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ecoexp
      - MYSQL_USER=ecoexp
      - MYSQL_PASSWORD=ecoexp
    restart: always
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - ./etc/mysql/utf.cnf:/etc/mysql/conf.d/utf.cnf
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8081:80
