/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ecoexp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.beans.factory.annotation.Autowired;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import ecoexp.core.eco.EcoProgramRepository;

@SpringBootApplication()
public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    @Autowired
    private EcoProgramRepository ecoProgramRepository;

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
